version: '3.7'

services:
  core:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn start:dev
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - .:/var/www/html/project/back
      - ./node_modules:/var/www/html/project/back/node_modules
    expose:
      - "${APP_PORT}"
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - chat-live-network

networks:
  chat-live-network:
    name: chat-live-network
    driver: bridge
